# Generated by Django 5.0.4 on 2024-04-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='users',
            new_name='user',
        ),
    ]
